var CUSTOMERS = {
	AZ : {
		LPCS : {
			name: "Las Puertas Community School",
			num_schools: 1,
			num_stu: "not available",
			num_interims: 0,
			url: "http://www.laspuertascommunityschool.org/",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "6-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		} 
	} ,
	CA : {
		SFUSD : {
			name: "San Francisco Unified School District",
			num_schools: 140,
			num_stu: 44000,
			num_interims: 3,
			grades: "3-11",
			url: "http://www.sfusd.edu",
			consortia: "Smarter Balanced",
			app: "Full Beacon",
			paper: "Yes",
			online: "Pending",
			num_summative: 0,
			testing_win1: "Sep 29 - Nov 14",
			testing_win2: "Dec 15 - Jan 23",
			testing_win3: "Mar 2 - Mar 27",
			testing_win0: "",
			testing_win4: "",
			testing_win5: ""
		},
		LAUSD : {
			name: "Los Angeles Unified School District",
			num_schools: 230,
			num_stu: 54000,
			num_interims: 0,
			url: "http://www.lausd.net",
			consortia: "Smarter Balanced",
			app: "Full Beacon",
			paper: "No",
			online: "Yes",
			num_summative: 1,
			grades: "",
			testing_win0: "",
			testing_win1: "May 25 - May 29",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		},
		MUSD : {
			name: "Mendota Unified School District",
			num_schools: 7,
			num_stu: 2600,
			num_interims: "--",
			url: "http://www.musdaztecs.com/",
			consortia: "Smarter Balanced",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "2-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		},
		PUC : {
			name: "PUC Schools",
			county: "Los Angeles",
			state: "California",
			num_schools: 16,
			num_stu: 4500,
			num_interims: "--",
			url: "http://www.pucschools.org/",
			consortia: "Smarter Balanced",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "2-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		},
		GPUSD : {
			name: "Golden Plains Unified School District",
			county: "Fresno",
			state: "California",
			num_schools: 6,
			num_stu: 1600,
			num_interims: "--",
			url: "http://www.gpusd.org/",
			consortia: "Smarter Balanced",
			app: "Full Beacon",
			paper: "",
			online: "Yes",
			num_summative: "--",
			grades: "K-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}  
	},
	DC : {
		DCPS : {
			name: "District of Columbia Public Schools",
			num_schools: 93,
			num_stu: 33000,
			num_interims: 4,
			url: "http://dcps.dc.gov/portal/site/DCPS/",
			consortia: "PARCC",
			app: "Full Beacon",
			paper: "Yes",
			online: "Yes",
			num_summative: "--",
			grades: "2-10",
			testing_win0: "Sep 2 - Sep 19 (pre-test)",
			testing_win1: "Sep 29 - Oct 7",
			testing_win2: "Nov 19 - Dec 2",
			testing_win3: "Feb 2 - Feb 10",
			testing_win4: "Mar 30 - Apr 28",
			testing_win5: "May 5 - Jun 12"
		},
		EAPCS: {
			name: "Eagle Academy Public Charter School District",
			num_schools: "2",
			num_stu: "900",
			num_interims: "--",
			url: "http://www.eagleacademypcs.org/",
			consortia: "PARCC",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: -1,
			grades: "K-3",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}  
	},
	DE : {
		NCCS : {
			name: "New Castle Charter Schools",
			num_schools: 4,
			num_stu: 1400,
			num_interims: "--",
			url: "http://nec.newcastledistrict.org/",
			consortia: "PARCC",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "3-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		} 
	},
	IL : {
		VIC : {
			name: "Victory Education Partners",
			num_schools: "--",
			num_stu: "--",
			num_interims: "--",
			url: "http://victoryep.com/",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}
	},
	IN : {
		EA : {
			name: "East Allen County Schools",
			county: "Allen",
			state: "Indiana",
			num_schools: 14,
			num_stu: 8600,
			num_interims: "--",
			url: "http://www.eacs.k12.in.us/",
			consortia: "none",
			app: "Assessment Studio only",
			paper: "",
			online: "Yes",
			num_summative: "--",
			grades: "2-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		} 
	},
	KY : {
		LCSD1 : {
			name: "Lexington County School District 01",
			num_schools: 1,
			num_stu: 0,
			num_interims: "--",
			url: "0",
			consortia: "0",
			app: "Full Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "2-5",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}
	},
	NC : {
		GPS : {
			name: "Guilford County Schools",
			county: "Guilford",
			state: "North Carolina",
			num_schools: 22,
			num_stu: 4000,
			num_interims: 0,
			url: "http://www.gcsnc.com/pages/gcsnc",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "6-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		},
		NHC : {
			name: "New Hanover County Schools",
			county: "New Hanover",
			state: "North Carolina",
			num_schools: 3,
			num_stu: 800,
			num_interims: "--",
			url: "http://www.gcsnc.com/pages/gcsnc",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "Yes",
			num_summative: "--",
			grades: "3-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		} 
	}, 
	NY : {
		ACH : {
			name: "Achievement First Public Charter Schools",
			num_schools: 11,
			num_stu: 5000,
			num_interims: "--",
			url: "http://www.achievementfirst.org/",
			consortia: "PARCC",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		},
		PAVE : {
			name: "PAVE Academy Charter School",
			num_schools: 1,
			num_stu: 225,
			num_interims: "--",
			url: "http://www.paveacademy.org/",
			consortia: "PARCC",
			app: "Full Beacon",
			paper: "Yes",
			online: "Yes",
			num_summative: "--",
			grades: "K-4",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		},
		UCS : {
			name: "Uncommon Schools",
			num_schools: 15,
			num_stu: 857,
			num_interims: "--",
			url: "http://www.uncommonschools.org/",
			consortia: "PARCC",
			app: "Full Beacon",
			paper: "Yes",
			online: "No",
			num_summative: "--",
			grades: "2-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}  
	},
	TN : {
		MSPS: {
			name: "Metro Nashville Public Schools",
			num_schools: 0,
			num_stu: 0,
			num_interims: "--",
			url: "0",
			consortia: "0",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "2-4",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}
	},
	VA : {
		CB : {
			name: "College Board",
			county: "various",
			state: "FL,TX, MD, IL, DC, SC,  DE, WA, OH, CA, VA, TN",
			num_schools: 115,
			num_stu: 10000,
			num_interims: "--",
			url: "http://www.collegeboard.org",
			consortia: "n/a",
			app: "Full Beacon",
			paper: "Yes",
			online: "Yes",
			num_summative: "--",
			grades: "6-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		} 
	},
	WA : {
		SPS : {
			name: "Seattle Public schools",
			county: "King",
			state:"Washington",
			num_schools: 42,
			num_stu: 6500,
			num_interims: 3,
			url: "http://www.seattleschools.org/",
			consortia: "Smarter Balanced",
			app: "Full Beacon",
			paper: "",
			online: "",
			num_summative: 2,
			grades: "2-12",
			testing_win0: "",
			testing_win1: "Sep 8 - Sep 19",
			testing_win2: "Nov 10 - Nov 21",
			testing_win3: "Feb 2 - Feb 13",
			testing_win4: "",
			testing_win5: ""
		} ,
		SPO : {
			name: "Spokane Public schools",
			num_schools: 23,
			num_stu: 11000,
			num_interims: "--",
			url: "http://www.spokaneschools.org",
			consortia: "Smarter Balanced",
			app: "Full Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "Sep 15 - Oct 3",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: ""
		}
	}
};