var CUSTOMERS = {
	AL : {
		TCSD : {
			name: "Tuscaloosa County School District",
			county: "Tuscaloosa",
			num_schools: "--",
			num_stu: "550",
			num_interims: 0,
			url: "www.tcss.net/site/default.aspx?PageID=1",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "tusc.png",
			motto: ""
		}
	},
	AZ : {
		LPCS : {
			name: "Las Puertas Community School",
			county: "Pima",
			num_schools: 1,
			num_stu: "75",
			num_interims: 0,
			url: "www.laspuertascommunityschool.org",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "Grades 6-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "lpcs.gif",
			motto: "Where you belong."
		} 
	} ,
	AR : {
		NSD : {
			name: "Newport School District",
			county: "Jackson",
			num_schools: "--",
			num_stu: "1,283",
			num_interims: 0,
			url: "www.newportschools.org/pages/Newport_School_District",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "newport.png",
			motto: "The tradition continues..."
		}
	},
	CA : {
		CARU : {
			name: "Caruthers Unified School District",
			county: "Fresno",
			num_schools: "--",
			num_stu: "1,200",
			num_interims: 0,
			url: "www.caruthers.k12.ca.us/",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "caru.png",
			motto: "Success through partnership."
		},
		CHOW : {
			name: "Chowchilla Union High School District",
			county: "Madera",
			num_schools: "--",
			num_stu: "1,000",
			num_interims: 0,
			url: "www.chowchillahigh.k12.ca.us/",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "chow.png",
			motto: "Redskin pride community wide."
		},
		COA : {
			name: "Community Outreach Academy",
			county: "Sacramento",
			num_schools: 2,
			num_stu: "1,200",
			num_interims: "--",
			url: "www.outreachacademy.org",
			consortia: "Smarter Balanced",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "Grades 2-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			motto: "",
			logo: "coa.png"
		},
		EARL : {
			name: "Earlimart Elementary School District",
			county: "",
			num_schools: "--",
			num_stu: "1,885",
			num_interims: 0,
			url: "earlimart.org",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "earl.png",
			motto: "Every child. Every opportunity. Every day."
		},
		ECP : {
			name: "Education for Change Public Schools",
			county: "Oakland",
			num_schools: "--",
			num_stu: "1,703",
			num_interims: "--",
			url: "efcps.org/",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "Grades K-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			motto: "",
			logo: "educhange.png"
		},
		GPUSD : {
			name: "Golden Plains Unified School District",
			county: "Fresno",
			num_schools: 6,
			num_stu: "1,941",
			num_interims: "--",
			url: "www.gpusd.org",
			consortia: "Smarter Balanced",
			app: "Beacon",
			paper: "",
			online: "Yes",
			num_summative: "--",
			grades: "Grades K-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			motto: "Whatever it takes...our kids are worth it!",
			logo: "goldenplains.png"
		},
		KING : {
			name: "Kingsburg Joint Union High School District",
			county: "Fresno",
			num_schools: "--",
			num_stu: "1,177",
			num_interims: 0,
			url: "khsvikings.com",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "kings.png",
			motto: "Home of the Vikings."
		},
		LAUSD : {
			name: "Los Angeles Unified School District",
			county: "Los Angeles",
			num_schools: 230,
			num_stu: "54,000",
			num_interims: 0,
			url: "www.lausd.net",
			consortia: "Smarter Balanced",
			app: "Beacon",
			paper: "No",
			online: "Yes",
			num_summative: 1,
			grades: "",
			testing_win0: "",
			testing_win1: "May 25 - May 29",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "lausd.png",
			motto: "All youth achieving."
		},
		MUSD : {
			name: "Mendota Unified School District",
			county: "Fresno",
			num_schools: 7,
			num_stu: "2,600",
			num_interims: "--",
			url: "www.musdaztecs.com",
			consortia: "Smarter Balanced",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "Grades 2-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "mendota.png",
			motto: "Building scholars, leaders, and champions!"
		},
		HOPE : {
			name: "St. Hope Public Schools",
			county: "Sacramento",
			num_schools: "--",
			num_stu: "1,665",
			num_interims: 0,
			url: "sthopepublicschools.org/",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "hope.png",
			motto: ""
		}, 
		TWIN : {
			name: "Twin River Charter School",
			county: "Sutter",
			num_schools: "1",
			num_stu: "360",
			num_interims: 0,
			url: "twinriverscharterschool.org",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "twin.png",
			motto: "Home of the Tigers!"
		},
		WATER : {
			name: "Waterford Unified School District",
			county: "Stanislaus",
			num_schools: "--",
			num_stu: "2,075",
			num_interims: 0,
			url: "waterford-ca.schoolloop.com/",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "books_icon.png",
			motto: ""
		} 
	},
	CT : {
		NH : {
			name: "New Haven Public Schools",
			county: "New Haven",
			num_schools: "--",
			num_stu: "517",
			num_interims: 0,
			url: "nhps.net",
			consortia: "",
			app: "",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "newhaven.png",
			motto: ""
		}
	},
	DC : {
		CITY : {
			name: "City Center Public Charter School",
			county: "District of Columbia",
			num_schools: 1,
			num_stu: "1,000",
			num_interims: "--",
			url: "centercitypcs.org",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "citycenter.png",
			motto: "Character, Excellence, Service"
		},
		DCPS : {
			name: "District of Columbia Public Schools",
			county: "District of Columbia",
			num_schools: 93,
			num_stu: "30,137",
			num_interims: 4,
			url: "dcps.dc.gov/portal/site/DCPS",
			consortia: "PARCC",
			app: "Beacon",
			paper: "Yes",
			online: "Yes",
			num_summative: "--",
			grades: "Grades 2-10",
			testing_win0: "Sep 2 - Sep 19 (pre-test)",
			testing_win1: "Sep 29 - Oct 7",
			testing_win2: "Nov 19 - Dec 2",
			testing_win3: "Feb 2 - Feb 10",
			testing_win4: "Mar 30 - Apr 28",
			testing_win5: "May 5 - Jun 12",
			logo: "dcps.png",
			motto: ""
		},
		EAPCS: {
			name: "Eagle Academy Public Charter School District",
			county: "District of Columbia",
			num_schools: "2",
			num_stu: "233",
			num_interims: "--",
			url: "www.eagleacademypcs.org",
			consortia: "PARCC",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: -1,
			grades: "Grades K-3",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "eagle.png",
			motto: "Starting early. Soaring high."
		}  
	},
	DE : {
		NCCS : {
			name: "Delaware Charter Schools",
			county: "New Castle",
			num_schools: 4,
			num_stu: "3,280",
			num_interims: "--",
			url: "",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "dela.png",
			motto: "Nurture. Inspire. Support."
		} 
	},
	GA : {
		RICH : {
			name: "Richmond County School System",
			county: "Richmond",
			num_schools: "--",
			num_stu: "150",
			num_interims: "--",
			url: "rcboe.org",
			consortia: "",
			app: "",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "richmond.png",
			motto: "Learning today. Leading tomorrow."
		} 
	},
	IL : {
		VIC : {
			name: "Victory Education Partners",
			county: "Cook",
			num_schools: "--",
			num_stu: "647",
			num_interims: "--",
			url: "victoryep.com/",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "victory.png",
			motto: "Helping communities create great schools."
		}
	},
	IN : {
		EA : {
			name: "East Allen County Schools",
			county: "Allen",
			state: "Indiana",
			num_schools: 14,
			num_stu: "7,806",
			num_interims: "--",
			url: "www.eacs.k12.in.us",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "Yes",
			num_summative: "--",
			grades: "Grades 2-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "eastallen.png",
			motto: "Dream it. Do it."
		} 
	},
  MI : {
		LCSD1 : {
			name: "Manistee Area Public Schools",
			county: "",
			num_schools: "--",
			num_stu: "1,691",
			num_interims: "--",
			url: "maps.manistee.org/",
			consortia: "",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "Grades 2-5",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "books_icon.png",
			motto: ""
		}
	},
	NC : {
		GPS : {
			name: "Guilford County Schools",
			county: "Guilford",
			state: "North Carolina",
			num_schools: 22,
			num_stu: "14,118",
			num_interims: 0,
			url: "www.gcsnc.com/pages/gcsnc",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: 0,
			grades: "Grades 6-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "guilford.png",
			motto: "Striving. Achieving. Excelling."
		},
		NHC : {
			name: "New Hanover County Schools",
			county: "New Hanover",
			state: "North Carolina",
			num_schools: 3,
			num_stu: 800,
			num_interims: "--",
			url: "www.nhcs.k12.nc.us",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "Yes",
			num_summative: "--",
			grades: "Grades 3-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "nhcs.png",
			motto: "Reach, Equip, Achieve."
		} 
	}, 
	NY : {
		NFTE : {
			name: "Network for Teaching Entrepreneurship",
			county: "New York",
			num_schools: "--",
			num_stu: 260,
			num_interims: "--",
			url: "nfte.com/what/programs/new-york-metro",
			consortia: "PARCC",
			app: "",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "nfte.png",
			motto: "Start it up."
		},
		PAVE : {
			name: "PAVE Academy Charter School",
			county: "New York",
			num_schools: 1,
			num_stu: 225,
			num_interims: "--",
			url: "www.paveacademy.org",
			consortia: "PARCC",
			app: "Beacon",
			paper: "Yes",
			online: "Yes",
			num_summative: "--",
			grades: "Grades K-4",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "pave.png",
			motto: "Building citizens and schools brick by brick."
		},
		PRO : {
			name: "Professional Preparatory Charter School",
			county: "Kings",
			num_schools: "--",
			num_stu: 205,
			num_interims: "--",
			url: "tfoaprofessionalprep.org/",
			consortia: "PARCC",
			app: "",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "pro_prep.png",
			motto: "Our deepest fear is that we are talented beyond measure..."
		},
		UCS : {
			name: "Uncommon Schools",
			county: "New York",
			num_schools: 15,
			num_stu: "1,691",
			num_interims: "--",
			url: "www.uncommonschools.org",
			consortia: "PARCC",
			app: "Beacon",
			paper: "Yes",
			online: "No",
			num_summative: "--",
			grades: "Grades 2-8",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "uncommon.png",
			motto: ""
		}  
	},
	SC : {
		LEX: {
			name: "Lexington County School District",
			county: "Lexington",
			num_stu: "575",
			num_schools: "--",
			grades: "",
			app: "Beacon",
			motto: "Where children and learning are One.",
			logo: "lex.png",
			url: "www.lexington1.net/",
			consortia: ""
		}
	},
	TN : {
		MSPS: {
			name: "Metro Nashville Public Schools",
			county: "Davidson",
			num_schools: "--",
			num_stu: "1,040",
			num_interims: "--",
			url: "",
			consortia: "",
			app: "Assessment Studio only",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "Grades 2-4",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "books_icon.png",
			motto: ""
		}
	},
	VA : {
		CB : {
			name: "College Board",
			county: "Fairfax",
			state: "VA",
			num_schools: 115,
			num_stu: "10,000",
			num_interims: "--",
			url: "www.collegeboard.org",
			consortia: "",
			app: "Beacon",
			paper: "Yes",
			online: "Yes",
			num_summative: "--",
			grades: "Grades 6-12",
			testing_win0: "",
			testing_win1: "",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "collegeboard.png",
			motto: ""
		} 
	},
	WA : {
		SPS : {
			name: "Seattle Public schools",
			county: "King",
			state:"Washington",
			num_schools: 42,
			num_stu: "6,500",
			num_interims: 3,
			url: "sps.ss8.sharpschool.com/",
			consortia: "Smarter Balanced",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: 2,
			grades: "Grades 2-12",
			testing_win0: "",
			testing_win1: "Sep 8 - Sep 19",
			testing_win2: "Nov 10 - Nov 21",
			testing_win3: "Feb 2 - Feb 13",
			testing_win4: "",
			testing_win5: "",
			logo: "seattle.png",
			motto: ""
		} ,
		SPO : {
			name: "Spokane Public schools",
			county: "Spokane",
			num_schools: 23,
			num_stu: "1,100",
			num_interims: "--",
			url: "www.spokaneschools.org",
			consortia: "Smarter Balanced",
			app: "Beacon",
			paper: "",
			online: "",
			num_summative: "--",
			grades: "",
			testing_win0: "",
			testing_win1: "Sep 15 - Oct 3",
			testing_win2: "",
			testing_win3: "",
			testing_win4: "",
			testing_win5: "",
			logo: "spokane.png",
			motto: "Excellence for everyone."
		}
	}
};