var data = 
    {
       menu: 
          [
            {title: 'Create The Perfect Color Scheme (Part 2 of 2)',
              subtitle: 'More tools to get smashing colors.',
              link: 'colormathPt2.html',
               image: 'triadic_thumb.png'},
            {title: 'Create The Perfect Color Scheme (Part 1 of 2)',
              subtitle: 'Interactive tools to get beautiful colors.',
              link: 'colormath.html',
               image: 'tetradic_palette.png'},
            {title: 'The Importance of a Creative Blackout Hour',
              subtitle: 'Sometimes you have to let your ideas go.',
              link: 'blackout.html',
               image: 'blackout_thumb.png'},
            {title: 'Quiz: Guess the Titles of these \'80s Teen Romance Novels',
              subtitle: 'They are incredible.',
              link: 'bookcovers.html',
               image: 'bookcovers/teaser.png'},
               {title: 'Who Needs A Spreadsheet When You Have Dye And Some Rope?',
              subtitle: '',
              link: 'quipu.html',
               image: 'quipu.png'},
            {title: 'Do You See What I See?',
                subtitle: 'If you speak a different language, you might not.',
               link: 'himba.html',
                image: 'himbaPhoto1.png'},
              {title: 'Visual Flashcards: Cocktails',
              subtitle: 'Never forget how to order your favorite drink.',
              link: 'drinks.html',
               image: 'dirty.png'},
             {title: 'Color Wheel for Coffee',
             subtitle: 'A visual aid for describing tastes.',
              link: 'coffee.html',
               image: 'flavorWheel.jpg'},
              {title: 'A Letter To St. Louis On Losing Their Football Team',
              subtitle: 'In short: Don\'t worry!',
              link: 'rams.html',
               image: 'audrey.png'},
             {title: 'Ancient Greeks Saw Things Differently, Literally',
             subtitle: '',
               link: 'greece.html',
                image: 'greece.jpg'},
            {title: 'First Versions: 3 Popular Games',
            subtitle: 'Some favorite games are actually knock-offs.',
              link: 'games.html',
               image: 'lego1949.png'},
            {title: 'Think Shakespeare\'s Bedroom was Drab?',
            subtitle: 'Think again.',
              link: 'shakes.html',
               image: 'shakes/red_green_650x865.jpg'}
          ]
    };


